# Generated by Django 4.2.1 on 2023-06-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0006_alter_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_thumbnail',
            field=models.ImageField(null=True, upload_to='images/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
