# Generated by Django 4.2.1 on 2023-06-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0007_post_post_thumbnail_alter_post_post_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='likepost',
            constraint=models.UniqueConstraint(models.F('user'), models.F('post'), name='unique_user_post'),
        ),
    ]
