# Generated by Django 4.2.1 on 2023-06-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0008_likepost_unique_user_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_superthumbnail',
            field=models.ImageField(null=True, upload_to='images/superthumbnails/'),
        ),
    ]
