# Generated by Django 4.2.1 on 2023-06-17 04:17

from django.db import migrations, models
import imagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0009_post_post_superthumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_image_ppoi',
            field=imagefield.fields.PPOIField(default='0.5x0.5', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='post_image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=imagefield.fields.ImageField(height_field='post_image_height', null=True, upload_to='images/', width_field='post_image_width'),
        ),
    ]
