# Generated by Django 4.2.1 on 2023-06-17 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0010_post_post_image_height_post_post_image_ppoi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_superthumbnail',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_thumbnail',
        ),
    ]
