# Generated by Django 4.2.2 on 2023-10-06 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0011_remove_post_post_superthumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('video_file', models.FileField(null=True, upload_to='videos/%Y/%m/%d/', verbose_name='')),
                ('video_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view.post')),
            ],
        ),
    ]
