# Generated by Django 4.2.2 on 2023-10-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0012_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
    ]
