# Generated by Django 4.2.2 on 2023-10-15 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0014_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('delete_own_post', 'Can delete their own post'), ('change_own_post', 'Can change their own post')]},
        ),
    ]
